Pulsados
lnls-sirius/bbb-function pull request #31
Opened 2022-04-12 15:28 UTC by danielegsouza

Foi adicionado a configuração de rede da spixconv via pendrive

2022-04-12 17:58 UTC, pnallin requested changes
I have added some comments! 
(src/scripts/eth-bridge-pru-serial485 is not necessary!)

2022-04-12 17:58 UTC, pnallin commented on src/scripts/devices.py
> +    persist_info(0, 0, " ","RESET", "Searching for connected equipments.")
Missing space (' ') after comma !

2022-04-12 17:58 UTC, pnallin commented on src/scripts/devices.py
> +        persist_info(Type.UNDEFINED, name,115200, NOTTY)
Missing space (' ') after comma !

2022-04-12 17:58 UTC, pnallin commented on src/scripts/devices.py
> +            persist_info(Type.MKS937B, name,baud, MKS937B, "MKS937Bs connected {}".format(devices))
Missing space (' ') after comma !

2022-04-12 17:58 UTC, pnallin commented on src/scripts/devices.py
> +            print(bbb[0])
Remove printing !

2022-04-13 14:47 UTC, pnallin approved these changes

2022-04-13 14:47 UTC, pnallin commented
Deixamos pra fazer o merge quando levarmos a aplicação lá pro Sirius!
Na parada de maio

2022-04-13 18:28 UTC, gfrn approved these changes

2022-04-27 15:42 UTC, closed without merging